# Generated by Django 3.2.25 on 2024-10-18 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=50)),
                ('recipient_street_address1', models.CharField(max_length=80)),
                ('recipient_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('recipient_town_or_city', models.CharField(max_length=40)),
                ('recipient_county', models.CharField(blank=True, max_length=80, null=True)),
                ('recipient_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_country', models.CharField(blank=True, max_length=40, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to='profiles.userprofile')),
            ],
        ),
    ]
