# Generated by Django 3.2.25 on 2024-10-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_recipientaddresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientaddresses',
            name='recipient_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
