# Generated by Django 3.2.25 on 2024-10-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_recipientaddresses_recipient_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientaddresses',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
