# Generated by Django 3.2.25 on 2024-10-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_pick_up'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='country',
            new_name='billing_country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='county',
            new_name='billing_county',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='billing_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='billing_full_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='billing_phone_number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='postcode',
            new_name='billing_postcode',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address1',
            new_name='billing_street_address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address2',
            new_name='billing_street_address2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='town_or_city',
            new_name='billing_town_or_city',
        ),
        migrations.AddField(
            model_name='order',
            name='different_delivery_address',
            field=models.BooleanField(default=False),
        ),
    ]
