# Generated by Django 3.2.25 on 2024-10-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20241017_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
